[Definition]
failregex = ^<HOST> - .* "(GET|POST|HEAD|PUT|DELETE|PATCH|OPTIONS) .*" 4\d\d \d+ ".*" ".*"$
            ^<HOST> - .* "(GET|POST|HEAD|PUT|DELETE|PATCH|OPTIONS) .*" 4\d\d \d+ .*$

ignoreregex =
